# Generated by Django 2.1.4 on 2018-12-13 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст ответа')),
                ('isTrue', models.BooleanField(verbose_name='Верный ответ?')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Текст вопроса')),
                ('image', models.ImageField(upload_to='media/images/', verbose_name='Картинка ответ')),
                ('short_image', models.ImageField(upload_to='media/images/', verbose_name='Картинка вопрос')),
                ('is_public', models.BooleanField(verbose_name='Опубликован?')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Наименование')),
                ('order_num', models.PositiveSmallIntegerField(default=0, verbose_name='Порядковый номер')),
                ('points', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Количество очков')),
                ('games_num', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='Отыграно раундов')),
            ],
            options={
                'verbose_name': 'Команда',
                'verbose_name_plural': 'Команды',
                'ordering': ['games_num', 'order_num'],
            },
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='app.Question', verbose_name='Вопрос'),
        ),
    ]
