# Generated by Django 2.1.4 on 2018-12-14 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20181214_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Опубликован?'),
        ),
    ]
